#!/bin/sh
#

$my_bin/FoLiA-alto > testfoliaalto.out 2>&1

$my_bin/FoLiA-alto -V >> testfoliaalto.out 2>&1

$my_bin/FoLiA-alto --help >> testfoliaalto.out 2>&1

rm -rf /tmp/cache  >> testfoliaalto.out 2>&1
rm -f out/dpo.*.folia.xml  >> testfoliaalto.out 2>&1

$my_bin/FoLiA-alto --cache=/tmp/cache -O out --type=boek data/test:mpeg21.xml >> testfoliaalto.out 2>&1

ls /tmp/cache >> testfoliaalto.out

ls out/dpo.*.folia.xml >> testfoliaalto.out
