#!/bin/sh -v
#

\rm *.ticcl.xml

$my_bin/FoLiA-correct > testcorrect.out 2>&1

$my_bin/FoLiA-correct -V >> testcorrect.out 2>&1

$my_bin/FoLiA-correct --help >> testcorrect.out 2>&1

$my_bin/FoLiA-correct --punct=punct.punct --unk=unk.unk --rank=rank.ranked --clear data/corr_str.xml >> testcorrect.out  2>&1

diff corr_str.ticcl.xml corr_str.ticcl.1.ok  >> testcorrect.out 2>&1

$my_bin/FoLiA-correct --punct=punct.punct --unk=unk.unk --rank=rank.ranked --clear --string-nodes data/corr_str.xml >> testcorrect.out  2>&1

diff corr_str.ticcl.xml corr_str.ticcl.2.ok  >> testcorrect.out 2>&1

$my_bin/FoLiA-correct --punct=punct.punct --unk=unk.unk --rank=rank.ranked --ngram=2 --clear data/corr.xml >> testcorrect.out  2>&1

diff corr.ticcl.xml corr.ticcl.2.ok  >> testcorrect.out 2>&1

$my_bin/FoLiA-correct --punct=punct.punct --unk=unk.unk --rank=rank.ranked --ngram=3 --clear data/corr.xml >> testcorrect.out  2>&1

diff corr.ticcl.xml corr.ticcl.3.ok  >> testcorrect.out 2>&1
