#!/bin/sh
#

$my_bin/FoLiA-abby > testabby.out 2>&1

$my_bin/FoLiA-abby -V >> testabby.out 2>&1

$my_bin/FoLiA-abby --help >> testabby.out 2>&1

$my_bin/FoLiA-abby -O out data/abby >> testabby.out 2>&1

./foliadiff.sh out/morse_OCR_perletter.folia.xml morse.ok  >> testabby.out 2>&1
./foliadiff.sh out/levi010geil01_01_Deel500.folia.xml levi.ok  >> testabby.out 2>&1
./foliadiff.sh out/piroska.abby.folia.xml piroska.abby.folia.ok  >> testabby.out 2>&1
