#!/bin/sh
#

$my_bin/FoLiA-langcat > testlangcat.out 2>&1

$my_bin/FoLiA-langcat -V >> testlangcat.out 2>&1

$my_bin/FoLiA-langcat --help >> testlangcat.out 2>&1

$my_bin/FoLiA-langcat --config=tc.txt -O out data/langcat.test.xml >> testlangcat.out 2>&1

cat out/langcat.test.lc.xml >> testlangcat.out

$my_bin/FoLiA-langcat --config=tc.txt -O out --all data/langcat.test2.xml >> testlangcat.out 2>&1

cat out/langcat.test2.lc.xml >> testlangcat.out

$my_bin/FoLiA-langcat --config=tc.txt -O out -s --all data/langcat.test-str.xml >> testlangcat.out 2>&1

cat out/langcat.test-str.lc.xml >> testlangcat.out

$my_bin/FoLiA-langcat --config=tc.txt -O out --tags=str --all data/langcat.test-str.xml >> testlangcat.out 2>&1

cat out/langcat.test-str.lc.xml >> testlangcat.out
