#!/bin/sh -v
#

\rm -rf clean/*

$my_bin/FoLiA-clean > testclean.out 2>&1

$my_bin/FoLiA-clean -V >> testclean.out 2>&1

$my_bin/FoLiA-clean --help >> testclean.out 2>&1

$my_bin/FoLiA-clean -O clean --cleanannoset=lang data/dirty.folia.xml >> testclean.out 2>&1
./foliadiff.sh clean/data/dirty.cleaned.folia.xml cleaned_lang.ok  >> testclean.out 2>&1
$my_bin/FoLiA-clean -O clean --cleanannoset=lang\\http://raw.github.com/proycon/folia/master/setdefinitions/iso639_3.foliaset data/dirty.folia.xml >> testclean.out 2>&1
./foliadiff.sh clean/data/dirty.cleaned.folia.xml cleaned_lang.ok  >> testclean.out 2>&1

$my_bin/FoLiA-clean -O clean --cleanannoset=lang --cleanannoset=pos --cleanannoset=entity --cleanannoset=lemma --textclass=OCR --current data/dirty.folia.xml >> testclean.out 2>&1
./foliadiff.sh clean/data/dirty.cleaned.folia.xml cleaned_all.ok  >> testclean.out 2>&1

$my_bin/FoLiA-clean -O clean --fixtext --textclass=OCR data/dirty2.folia.xml >> testclean.out 2>&1
./foliadiff.sh clean/data/dirty2.cleaned.folia.xml clean_fix.ok  >> testclean.out 2>&1
