#!/bin/sh
#

$my_bin/FoLiA-2text > testfolia2text.out 2>&1
$my_bin/FoLiA-2text -V >> testfolia2text.out 2>&1
$my_bin/FoLiA-2text --help >> testfolia2text.out 2>&1

$my_bin/FoLiA-2text -o out data/folia.xml
cat out/data/folia.xml.txt >> testfolia2text.out

$my_bin/FoLiA-2text -o out --class=anders data/folia.xml
cat out/data/folia.xml.txt >> testfolia2text.out
