#!/bin/sh -v
#

rm *.tsv

$my_bin/FoLiA-stats > teststats.out 2>&1

$my_bin/FoLiA-stats -V >> teststats.out 2>&1

$my_bin/FoLiA-stats --help >> teststats.out 2>&1

$my_bin/FoLiA-stats --INTERNAL_TEST >> teststats.out 2>&1

$my_bin/FoLiA-stats -s --class=OCR --lang="none" -o stats -e dpo out/ > out1 2>&1
diff stats.wordfreqlist.tsv stats-1.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --ngram=3 -s --class=OCR --lang="none" -o stats -e dpo out/ > out2 2>&1
diff stats.wordfreqlist.3-gram.tsv stats-3.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --ngram=3 -S --class=OCR --lang="none" -o statS -e dpo out/ > out3 2>&1
diff statS.wordfreqlist.3-gram.tsv statS-3.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --max-ngram=3 -S --class=OCR --lang="none" -o statS1 -e dpo out/ > out4 2>&1
diff statS1.wordfreqlist.tsv statS1.ok >> teststats.out 2>&1
diff statS1.wordfreqlist.2-gram.tsv statS1-2.ok >> teststats.out 2>&1
diff statS1.wordfreqlist.3-gram.tsv statS1-3.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --ngram=3 --max-ngram=3 -S --class=OCR --lang="none" -o statS2 -e dpo out/ > out5 2>&1
diff statS2.wordfreqlist.3-gram.tsv statS2-3.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --tags=p --class=OCR --languages="skip,eng" -o stats1 out/langcat.test.lang.xml > out6 2>&1
diff stats1.wordfreqlist.eng.tsv stats-eng.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR --languages="eng,nld,fra,deu" -o stats2 data/statstest.xml > out7 2>&1
diff stats2.wordfreqlist.eng.tsv stats-eng.ok >> teststats.out 2>&1
diff stats2.wordfreqlist.nld.tsv stats-nld.ok >> teststats.out 2>&1
diff stats2.wordfreqlist.fra.tsv stats-fra.ok >> teststats.out 2>&1
diff stats2.wordfreqlist.deu.tsv stats-deu.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --tags=p --class=OCR --languages="skip,eng,nld,fra" -o stats3 data/statstest.xml > out8 2>&1
diff stats3.wordfreqlist.eng.tsv stats-eng.ok >> teststats.out 2>&1
diff stats3.wordfreqlist.nld.tsv stats-nld.ok >> teststats.out 2>&1
diff stats3.wordfreqlist.fra.tsv stats-fra.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR --languages="all" -o stats4 data/statstest.xml > out9 2>&1
diff stats4.wordfreqlist.deu.tsv stats-deu.ok >> teststats.out 2>&1
diff stats4.wordfreqlist.eng.tsv stats-eng.ok >> teststats.out 2>&1
diff stats4.wordfreqlist.nld.tsv stats-nld.ok >> teststats.out 2>&1
diff stats4.wordfreqlist.fra.tsv stats-fra.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR --ngram=2 --underscore -o stats5 data/statstest.xml > out10 2>&1
diff stats5.wordfreqlist.2-gram.tsv stats-under.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR --ngram=2 --separator='°' -o stats6 data/statstest.xml > out11 2>&1
diff stats6.wordfreqlist.2-gram.tsv stats-o.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR -o stats7 --languages=all --aggregate data/statstest.xml > out12 2>&1
diff stats7.agg.freqlist.tsv stats-agg.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=lemma_pos -o stats8 data/frog*.xml > out13 2>&1
diff stats8.wordfreqlist.tsv stats-words.ok >> teststats.out 2>&1
diff stats8.lemmafreqlist.tsv stats-lemmas.ok >> teststats.out 2>&1
diff stats8.lemmaposfreqlist.tsv stats-lempos.ok >> teststats.out 2>&1
cat out13 >> teststats.out

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR -o stats9 --languages=none -p data/statstest.xml > out14 2>&1
diff stats9.wordfreqlist.tsv stats9-perc.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR -o stats10 --languages=none -p --max-ngram=3 data/statstest.xml > out15 2>&1
diff stats10.wordfreqlist.tsv stats9-perc.ok >> teststats.out 2>&1
diff stats10.wordfreqlist.2-gram.tsv stats10-2.ok >> teststats.out 2>&1
diff stats10.wordfreqlist.3-gram.tsv stats10-3.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR -o stats11 --languages=all -p --max-ngram=3 data/statstest.xml > out16 2>&1
diff stats11.wordfreqlist.deu.tsv stats11-deu.ok >> teststats.out 2>&1
diff stats11.wordfreqlist.deu.2-gram.tsv stats11-deu-2.ok >> teststats.out 2>&1
diff stats11.wordfreqlist.deu.3-gram.tsv stats11-deu-3.ok >> teststats.out 2>&1
diff stats11.wordfreqlist.nld.tsv stats11-nld.ok >> teststats.out 2>&1
diff stats11.wordfreqlist.nld.2-gram.tsv stats11-nld-2.ok >> teststats.out 2>&1
diff stats11.wordfreqlist.nld.3-gram.tsv stats11-nld-3.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=lemma_pos --max-ngram=4 -o stats12 data/sonar*.xml > out17 --separator=_ 2>&1
diff stats12.wordfreqlist.tsv stats-words-son.ok >> teststats.out 2>&1
diff stats12.lemmafreqlist.tsv stats-lemmas-son.ok >> teststats.out 2>&1
diff stats12.lemmaposfreqlist.tsv stats-lempos-son.ok >> teststats.out 2>&1
diff stats12.wordfreqlist.4-gram.tsv stats-words-son-4.ok >> teststats.out 2>&1
diff stats12.lemmafreqlist.4-gram.tsv stats-lemmas-son-4.ok >> teststats.out 2>&1
diff stats12.lemmaposfreqlist.4-gram.tsv stats-lempos-son-4.ok >> teststats.out 2>&1
cat out17 >> teststats.out

$my_bin/FoLiA-stats --mode=text_in_par --class=OCR -o stats13 -p --max-ngram=3 --collect data/statstest.xml --separator=_ > out18 2>&1
diff stats13.wordfreqlist.1to3.tsv stats13.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=lemma_pos -o stats14 -p --max-ngram=4 --collect data/sonar*.xml --separator=_ > out19 2>&1
diff stats14.wordfreqlist.1to4.tsv stats14.word.ok >> teststats.out 2>&1
diff stats14.lemmafreqlist.1to4.tsv stats14.lemma.ok >> teststats.out 2>&1
diff stats14.lemmaposfreqlist.1to4.tsv stats14.lemmapos.ok >> teststats.out 2>&1

if [ "$NO_TICCL" = "" ]
then
    $my_bin/TICCL-mergelex -p -o BLA stats12.wordfreqlist.tsv stats12.wordfreqlist.2-gram.tsv stats12.wordfreqlist.3-gram.tsv stats12.wordfreqlist.4-gram.tsv > out20 2>&1
    diff  BLA.wordfreqlist.tsv stats14.word.ok >> teststats.out 2>&1
fi

$my_bin/FoLiA-stats --mode=text_in_par -o stats15 -p data/folia2.xml --detokenize --max-ngram=4 --collect > out21 2>&1
diff stats15.wordfreqlist.1to4.tsv stats15.word.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --mode=text_in_par -o stats16 -p data/folia2.xml --max-ngram=4 --collect > out22 2>&1
diff stats16.wordfreqlist.1to4.tsv stats16.word.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --max-ngram=4 --separator='_' --collect --tags=div --hemp=hemp1.txt -o stats17 -p data/hemp/hemptest.xml > out23 2>&1
diff stats17.hemp1.txt hemp1.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats --tags=p --skiptags=note -o stats18 data/p_note_test.xml > out24 2>&1
diff stats18.wordfreqlist.tsv stats-p_note.ok >> teststats.out 2>&1

$my_bin/FoLiA-stats -s --class=OCR --lang="none" --inputfiles=dpo.lst -e dpo > out25 2>&1
diff DPO2/wordfreqlist.tsv dpo.ok >> teststats.out 2>&1
