#!/bin/sh -x
#

$my_bin/FoLiA-collect > testcollect.out 2>&1

$my_bin/FoLiA-collect -V >> testcollect.out 2>&1

$my_bin/FoLiA-collect --help >> testcollect.out 2>&1

$my_bin/FoLiA-collect --ngram=2 -O collected -t1 . >> testcollect.out 2>&1

cat collected.* >> testcollect.out
