#!/bin/sh
#

$my_bin/FoLiA-abby > testabby.out 2>&1

$my_bin/FoLiA-abby -V >> testabby.out 2>&1

$my_bin/FoLiA-abby --help >> testabby.out 2>&1

$my_bin/FoLiA-abby -O out data/abby >> testabby.out 2>&1

./foliadiff.sh out/FA-morse_OCR_perletter.folia.xml morse.ok  >> testabby.out 2>&1
./foliadiff.sh out/FA-levi010geil01_01_Deel500.folia.xml levi.ok  >> testabby.out 2>&1
./foliadiff.sh out/FA-piroska.abby.folia.xml piroska.ok  >> testabby.out 2>&1

$my_bin/FoLiA-abby --addbreaks -O outbreak data/abby >> testabby.out 2>&1

./foliadiff.sh outbreak/FA-morse_OCR_perletter.folia.xml morse.break.ok  >> testabby.out 2>&1
./foliadiff.sh outbreak/FA-levi010geil01_01_Deel500.folia.xml levi.break.ok  >> testabby.out 2>&1
./foliadiff.sh outbreak/FA-piroska.abby.folia.xml piroska.break.ok  >> testabby.out 2>&1
