#!/bin/sh
#

$my_bin/FoLiA-page > testpage.out 2>&1

$my_bin/FoLiA-page -V >> testpage.out 2>&1

$my_bin/FoLiA-page --help >> testpage.out 2>&1

$my_bin/FoLiA-page -O out/page data/page >> testpage.out 2>&1

wc out/page/00*.tif.folia.xml >> testpage.out
$my_bin/foliadiff.sh out/page/00539791a.tif.folia.xml page.folia.xml.ok >> testpage.out
