#!/bin/sh
#

$my_bin/FoLiA-txt > testfoliatxt.out 2>&1

$my_bin/FoLiA-txt -V >> testfoliatxt.out 2>&1

$my_bin/FoLiA-txt --help >> testfoliatxt.out 2>&1

$my_bin/FoLiA-txt -O out data/test.txt
cat out/test.folia.xml >> testfoliatxt.out

$my_bin/FoLiA-txt --class=foobar -O out data/test.txt
cat out/test.folia.xml >> testfoliatxt.out

$my_bin/FoLiA-txt --class=bar --setname=foo -O out data/test.txt
cat out/test.folia.xml >> testfoliatxt.out
