#!/bin/sh
#

$my_bin/FoLiA-idf > testidf.out 2>&1

$my_bin/FoLiA-idf -V >> testidf.out 2>&1

$my_bin/FoLiA-idf --help >> testidf.out 2>&1

$my_bin/FoLiA-idf --class=OCR -O out1 -e alto.folia.xml out >> t1.out

wc out1.idf.tsv >> testidf.out 2>&1

$my_bin/FoLiA-idf --class=OCR --lower -O out2 -e alto.folia.xml out >>t2.out

wc out2.idf.tsv >> testidf.out 2>&1
