#!/bin/sh -v
#

foliadiff=foliadiff.sh

$my_bin/FoLiA-merge > testmerge.out 2>&1

$my_bin/FoLiA-merge -V >> testmerge.out 2>&1

$my_bin/FoLiA-merge --help >> testmerge.out 2>&1

$my_bin/FoLiA-merge --lemmas=merge/greek.lex merge/greek.xml >> testmerge.out  2>&1

$foliadiff greek.merged.xml merged.ok  >> testmerge.out 2>&1
