.TH FoLiA-page 1 "2014 sep 03"

.SH NAME
FoLiA-page - Convert PAGE files into FoLiA.

.SH SYNOPSIS
FoLiA-page [options] FILE

FoLiA-page [options] DIR

.SH DESCRIPTION

When a DIR is provided,
.B FoLiA-page
will process all files in DIR and store the result in DIR, or in
the directory provided with
.B -O

When a FILE is provided,
.B FoLiA-page
will process that file and store its result in the directory where FILE is
found or in the directory provided with
.B -O

All files should be in PAGE XML format or BZIP2 or GZ versions thereof.
When the input file(s) are zipped, the output will be too.

.SH OPTIONS
.B --compress
kind
.RS
Use BZIP2 compression (kind=b) or GZIP compression (kind=g)
.RE

.B -O
prefix
.RS
use 'prefix' as a directory name to store the page-ed files in.
.RE

.B --setname
set
.RS
The FoLiA set of the <str> nodes that are created. (default FoLiA-page-set).
.RE

.B --class
classname
.RS
The FoLiA classname of the <str> nodes that are created. (default OCR).
.RE

.B -t
number
.RS
Number of concurrent threads to be used by the program.
.RE

.B -v
.RS
be more verbose.
.RE

.B -V
.RS
Show VERSION
.RE

.B -h
.RS
Show some help
.RE

.SH BUGS
possible

.SH AUTHORS
Ko van der Sloot: Timbl@uvt.nl

Martin Reynaert: reynaert@uvt.nl
