.TH FoLiA-pm 1 "2020 mar 25"

.SH NAME
FoLiA-pm - Convert Political Mashup XML files into FoLiA.

.SH SYNOPSIS
FoLiA-pm [options] FILE

FoLiA-pm [options] DIR

.SH DESCRIPTION

When a DIR is provided,
.B FoLiA-pm
will process all files in DIR and store the result in DIR, or in
the directory provided with
.B -O

When a FILE is provided,
.B FoLiA-pm
will process that file and store its result in the directory where FILE is
found or in the directory provided with
.B -O

All files should be in the Political Mashup XML format.

.SH OPTIONS
.B --nosplit
.RS
Don't create separate topic files. (default is to do so)
.RE

.B -O
outdir
.RS
use 'outdir' as a directory name to store the pm-ed files in.
.RE

.B --prefix
prefix
.RS
use 'prefix' as a prefix for ALL xml:id's created. Default is FPM-. Use 'none'
for no prefix. A prefix may be needed for files with non NCname characters in
their names.
.RE


.B -t
or
.B
--threads
number
.RS
Number of concurrent threads to be used by the program.
.RE

.B -v
.RS
be more verbose.
.RE

.B -V
.RS
Show VERSION
.RE

.B -h
or
.B --help
.RS
Show some help
.RE

.SH BUGS
possible

.SH AUTHORS
Ko van der Sloot

Martin Reynaert

e\-mail: lamasoftware@science.ru.nl
